### ISSUE TITLE
Fee-Limit-PPM also for econ-handle

### ISSUE THREAD

**Issue by ziggie1984** [rkfg/regolancer#13]
I am having the usecase that I am increasing the fee-ppm for channels which are drained under a specific amount to very high values. Now it happens  when selecting econ_ratio (which I want) that rebalance-fees are very high. Should we also include the possibility of a  ppm limit when using econ_ratio?

**Comment by rkfg** [comment]
That's a valid concern, I think a new parameter should be added for that like `--econ-ratio-max-ppm` to reflect that it's only for this case.

**Comment by ziggie1984** [comment]
I will take it if that's ok for you ?

**Comment by rkfg** [comment]
Sure, and thank you!
