### ISSUE TITLE
[enhancement-request] automated rebalancing based on forwards

### ISSUE THREAD

**Issue by dekdynamics** [rkfg/regolancer#17]
Hi,

This seems like quite an interesting project. I use lntop already and notice rkfg is a frequent contribute there. I am currently using jet to do some automated rebalancing, but I am always looking for ways to improve the process. 

The main feature missing for me in regolancer is "forward based rebalancing". 

Say my node completes a forward as follows:

Node A -> Node B
ppm earned 1000
amount forwarded 100,000 sats

This automation, after detecting the forward, would try to quickly move the funds in the opposite direction, for less than we earned.

Node B -> Node A
ppm limit 1000
amount target: 100,000 sats

It would also be nice to set a percentage target for the ppm limit. So I could say "spend up to 80%" of the earnings in order to complete this rebalance. 

As a bonus feature, it could be useful to set local and remote balance thresholds on when to trigger the automatic rebalancer. 

Cheers,
The Wall

**Comment by rkfg** [comment]
I believe what you're describing is already present as `--econ-ratio`. You can set a coefficient to automatically limit the rebalancing fee, in the case you've described that'd be 1 (same fee) but you can set it to 0.8 (which means 80%) and then regolancer would try to rebalance for 1000*0.8 == 800 ppm.

I don't think automation falls in scope of the project, it can be done with external tools. Maybe in the future it would make sense to split the project in two, one as a library to include in other projects and another just a CLI interface that parses the parameters and config and runs the library.

**Comment by dekdynamics** [comment]
That is understandable. Might as well close this as out of scope.

**Comment by rkfg** [comment]
I mean this is clearly already a tool that automates payments to yourself 😅 But it's not a kind of tool that sits in the background and reacts to external events. I currently don't like the split between `params` and `regolancer` struct, both are used in most functions but the former contains raw parameters and the latter has transformed or indexed values. To allow using it as a dependency it should be unified and those parameters should be copied to the struct to decouple config/CLI from the main logic.

But if you feel adventurous you can write a tool that listens to lnd and simply launches regolancer with some parameters/config.
