### ISSUE TITLE
Deprecating allow-unbalance

### ISSUE THREAD

**Issue by rkfg** [rkfg/regolancer#21]
Looks like it's more confusing than useful. Should we maybe allow it by default (i.e. allow any channel to go below/above 50%) and show a notice that it doesn't have any effect if specified? Looks like in most use cases the operator doesn't care if the source channel goes too much down or the target goes up and the channels that are active in both directions don't need any rebalances at all and can be excluded. My (possibly wrong) reasoning was that channel should have liquidity in both directions to be useful. But in reality most channels favor only one direction and you need to rebalance for the opposite so it makes sense to remove any limitations for that.

Thoughts?

**Comment by ziggie1984** [comment]
I agree with your reasoning, so I would also argue that the allow-unbalance feature was in a way a bit dangerous when not specifying an amount or `rel-amount` it would lead to complete draining of the side, which maybe was not intended. So I think `pto` and `pfrom` are way more than enough, but still including those channels which are not balanced (50/50) in case `to` or `from` are not specified.

Moreover what also tends to confuse people is the reason that `pfrom` relates to the remote balance, most users who want to rebalance a source channel which is under 30% local, tend to use pfrom=30, although what they really mean it they want to even go above remote balance of 70%, meaning they should use pfrom=90 or something. 

So I also tend to remove unbalance feature and maybe also reference pfrom to local-balance as well ?

**Comment by rkfg** [comment]
I honestly don't understand what's so confusing with pfrom/pto. They're symmetrical and mean the max balance on remote or your side to consider the channel as source/target. It's of course possible to add alternative parameters such as `--min-local-percent-from=` and `--max-local-percent-to=` but to me those are even more confusing because one declares a minimum and another a maximum.

Regarding the amount, by default if it's not specified it's set on every attempt to rebalance the channel to 50/50 (whichever amount is lower). I suppose it's not documented and the reasoning is the same as I described in the OP. This logic was developed before `--rel-amount` when it made sense. Maybe if the amount isn't specified neither by `-a` nor `--rel-amount` we should error out instead.

**Comment by ziggie1984** [comment]
> I honestly don't understand what's so confusing with pfrom/pto. They're symmetrical and mean the max balance on remote or your side to consider the channel as source/target. It's of course possible to add alternative parameters such as --min-local-percent-from= and --max-local-percent-to= but to me those are even more confusing because one declares a minimum and another a maximum.

Agree, additional parameters would be more confusing, lets stick to pfrom for the remote balance.

Hmm I would not error out in case no `-a` or `--rel-amount` is specified, it will always tend to bring channels back to 50/50 which I like.

**Comment by rkfg** [comment]
TODO:
- [ ] deprecate `allow-unbalance-from/to`
- [ ] document zero/unspecified amount
