### ISSUE TITLE
[Request] Add absoluteto (ato) and absolutefrom (afrom)

### ISSUE THREAD

**Issue by MEdGalo** [rkfg/regolancer#25]
I'm more interested in the absolute balances from my channels, rather than relative balances. Can you please add this option?

**Comment by rkfg** [comment]
Shouldn't be hard but can you please describe your use case? In my understanding specific numbers don't matter much, only percentage.

**Comment by MEdGalo** [comment]
In case of 'from' channels that vary a lot in size, it's nice to have an absolute border. For outbound channels I don't have a use case, but If you add it for 'from', it would make sense to also add it for 'to' channels.

**Comment by rkfg** [comment]
They do vary I just don't understand why the absolute amount is important at all.

**Comment by MEdGalo** [comment]
Because there are channels that I would want to drain as much as possible, so that it can give me as much as possible inbound liquidity on that channel.

**Comment by rkfg** [comment]
In that case you can simply enable rapid rebalance, it will repeat the attempt until it fails. Otherwise the regular `--amount` option should do.
