### ISSUE TITLE
Channel candidate selection issue in getChannelCandidates

### ISSUE THREAD

**Issue by silenzara** [rkfg/regolancer#26]
I just noticed there is an issue with picking source channels if the intended source channel is in the `exclude_channels_in` list.

If I specify `--from xyz and --exclude-channel-in xyz` the xyz channel will be skipped completely. The reason is the `continue` in the `			if _, ok := r.excludeIn[c.ChanId]; ok` check in `getChannelCandidates` (line 50 atm). It will skip all the code underneath it and not add the channel to the from list.

I also think that piece of code should be brought up before the balance check since it's not needed to check the balance if the channel is excluded.

**Comment by rkfg** [comment]
Thank you, it's a known issue. It will be addressed in #24 as soon as it's merged. Stay tuned! Regarding the balance, agree, would be better to check that first.

**Comment by rkfg** [comment]
Fixed in v1.7.0
