### ISSUE TITLE
Add a parameter to substitute -a (Amount) with a relative target

### ISSUE THREAD

**Issue by TrezorHannes** [rkfg/regolancer#3]
When rebalancing, an absolute target to rebalance isn't always appropriate, especially when using a range of --pto.
Is it possible to add a percentage target, eg --per=0.7, to enable a range of targets to be filled up and the routine not stopping, until a percentage of 70% inbound is reached?

It's relevant for a larger node-runner, who has like 10 or more channels with < 10% outbound. 
Ideally the rebalancer is running, until it hits a desired target with all channels market as target, with desired outbound at X %

**Comment by rkfg** [comment]
I think there should be two parameters then, one that sets the target as `capacity * per / 100` and calculates the amount for every attempt as `capacity * per / 100 - local_balance`, and another to make it run until there are no source or target channels. Shouldn't be hard to implement.

**Comment by rkfg** [comment]
I think this issue is now resolved with both #12 and #18 merged.
