### ISSUE TITLE
Failing rapid rebalance

### ISSUE THREAD

**Issue by MEdGalo** [rkfg/regolancer#32]
Hi,

The rapid-rebalance attemps from regolancer seem to fail often with this error code: "Error building route: rpc error: code = Unknown desc = no matching outgoing channel available for node 0 (<myNodeId>)". 
What is going wrong here?

**Comment by rkfg** [comment]
Could it be that the channel in question was disabled suddenly? I personally never had this issue so can only guess but it's an error that lnd returns, not us.

**Comment by ziggie1984** [comment]
It could be either that your channel was disabled but there could be also some additional factors which lead lnd to not find a channel for the rebalance. For example, this channel got a forward just when you tried to send the payment leading not enough liquidity on your side to please the reserve. There might also be the case that you are in a situation where you have a stuck channel although most of the balance is on your side (see https://github.com/lightning/bolts/issues/728). As rkfg mentioned above the rebalancer behaves as it should and lnd just cannot find a suitable channel anymore. During which rapid rebalance attempt does it normally show you this message, is it only on the same channel ... ?

**Comment by rkfg** [comment]
I saw a similar error but for the last node, so it was about the channel to my node. That channel was disabled to me by the peer but the peer was online and active. I suppose this error in your case means that the channel from you to the first node on route is disabled for whatever reason. In any case that's not our issue.
