### ISSUE TITLE
Question about --lost-profit

### ISSUE THREAD

**Issue by feelancer21** [rkfg/regolancer#40]
I have a question about the description of the lost-profi option

```
-l, --lost-profit            also consider the outbound channel fees when looking for profitable routes so that outbound_fee+inbound_fee < route_fee
```

I think you mean the lost-profit on the outgoing channel as `outbound_fee` in the inequality. But hasn't it to be `route_fee + outbound_fee < inbound_fee` or more exactly `route_fee + outbound_fee < inbound_fee * econ_ratio`? Equivalent would be `route_fee < inbound_fee - outbound_fee` or `route_fee < inbound_fee * econ_ratio - outbound_fee`. Imho the last one is implemented.

**Comment by rkfg** [comment]
I think you're right, the last inequality is most informative, thanks!

**Comment by feelancer21** [comment]
Thanks for fixing it. Cannot ignore such math stuff and was little bit confused ;-).
