### ISSUE TITLE
Accelerator for rapid-rebalance

### ISSUE THREAD

**Issue by feelancer21** [rkfg/regolancer#43]
The rapid-rebalance is great. But it has the "disadvantage" that it can leads to an huge number of payments if there is a lot to rebalance and the amount is very low. 

I'd like to propose an accelerator. First rebalance is with the amount given by the user. The first rapid-rebalance is with the double amount and with each following step the amount doubles, e.g. 20k, 40k, ..., 20k * 2^i.
If one rapid-rebalance  (i>0) fails go back to i=0 and start the acceleration sequence again. Stop the whole rebalance if a rebalance with i=0 fails.

Edit:
Some thoughts how you can decrease the number of payments even more.
After the first rapid-rebalance sequence as proposed you have rebalanced $amount \cdot (2^{i+1}-1)$ overall. Now you can try rebalancing $amount \cdot 2^{i}$ again. Then go backward to $amount \cdot 2^{i-1}$, independently whether the trial before failed or succeeded. Then take $amount \cdot 2^{i-2}$. etc until you have reached the orginal amount again.

Example: There is a theorethical amount of 5000k which you could rebalance on a route. If you take an amount of 20k you have to repeat 250 times with current rapid-rebalancing. With the acceleration you rebalance 20k, ...., 1280k (7 steps). 2560k fails, because you have already rebalanced 2540k and only 2460k are free. Then test 20k, ...., 1280k again. Except 80k all will succeed. Overall you had 15 payment trials on this route.

**Comment by ziggie1984** [comment]
I like this feature too, I will give it a shot implementing it.
