### ISSUE TITLE
Lost_Profit feature and Lnd QueryRoutes seem not to work

### ISSUE THREAD

**Issue by ziggie1984** [rkfg/regolancer#5]
Thanks for this new feature. Just tested it, but it seems that as soon as the value is negative lnd throws it away and uses the default value of 5%:

```
2022/10/01 15:42:24 Attempt #1, amount: 100000 (max fee: -2)
Total fee: 21

ROUTE X 

2022/10/01 15:42:28 Success! Paid 21 in fees


```

Seems like a check if its negative needs to be done by regolancer itself ?

**Comment by rkfg** [comment]
Can you recheck with the latest commit please?

**Comment by ziggie1984** [comment]
LGTM 👍
