### ISSUE TITLE
Feature Proposal: Running until all channels are rebalanced

### ISSUE THREAD

**Issue by StefanoFedeli** [rkfg/regolancer#58]
At the moment from my experience the program completes after only 1 successful rebalance attempt. This means I have to run it again and again until the program cannot find any more at least 1 source and 1 destination channel based on my filters.

Could be possible to automate this manual proceduce or it was designed like this by choice? 

Thank you for the help

**Comment by rkfg** [comment]
Yes, it was designed like this. You can run it in a simple loop like this:
`while true; do regolancer -a 10000 --to=some_node_pk --pfrom=100 -r 0.7 || sleep 3600; done`
So if it exits with an error you pause the loop for an hour and then try again. This way you can react to errors flexibly, for example you might try to reset the lnd's mission control on error to retry all the routes again, or you may exit the loop completely.
