### ISSUE TITLE
Relative amounts cannot be included in the json config

### ISSUE THREAD

**Issue by StefanoFedeli** [rkfg/regolancer#59]
I'm trying to include _--rel-amount-to_ and   _--rel-amount-from_  in my config.json but both values are not recognized. Both as they are written here and using underscore instead of dashes.

**Comment by rkfg** [comment]
Looks like the toml/json fields were missing for these two, thanks for reporting. Can you check the `master` branch? Should work now.

**Comment by StefanoFedeli** [comment]
Great! Now it works. Not sure if the different naming (rem instead of rel) was done on purpose but it is working at least.

**Comment by rkfg** [comment]
That's a typo, of course, fixed it to be consistent with TOML. Thanks!
