### ISSUE TITLE
Have `econ-ratio-max-ppm ` account for source channel fee rate as well, when `--lost-profit` is enables 

### ISSUE THREAD

**Issue by KnockOnWoodNode** [rkfg/regolancer#60]
Currently, econ ratio is first processed and then adjusted with lost profit, and then, if econratiomaxppm exists, the resulting value will be furter limited:
https://github.com/rkfg/regolancer/blob/fb578adc0169e6efffe03222390dbe5815bc11fc/routes.go#L73

This means that when econratiomaxppm is lower than econratio-lostprofit, it will be used 100% without lost profit.

Wouldn't it be more appropriate to move up the check of the econratiomaxppm option, and after that apply the lostprofit, whether it is over econratio or a lower maxppm?

**Comment by rkfg** [comment]
Do you have a situation demonstrating this with concrete numbers? As I understand it, if `EconRatioMaxPPM` is set and the calculated fee (adjusted for lost profit) is greater than this parameter, we instead limit by `EconRatioMaxPPM` which is lower and as such should be more profitable than before the check. Just as the user wanted.

**Comment by KnockOnWoodNode** [comment]
I've been chatting with Ziggie about this on plebnet, and he explained to me how the current behaviour is what was originally intended, I cannot provide specific cases to aid in my idea, it was just an idea I had that seemed logic to me when I was thinking about using the econmaxppm setting. I would want my econmaxppm to be adjusted with the source channel's ppm no matter what but that is  just my preference, not particularly important because I can do the math in my script and just feed a maxfeeppm without using econratio and lostprofits :-)

**Comment by rkfg** [comment]
Yeah, I think if it doesn't cause unexpected fees and follows the explained logic, there's no problem with it so it's out of the scope.
